services:
  digihome-db:
    image: pgvector/pgvector:pg18-trixie
    container_name: digihome-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-myusername}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-digihome}
    volumes:
      - digihome_db_data:/var/lib/postgresql
    networks:
      - digihome-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -q"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  digihome_db_data: {}
